version: '3.6'

services:
  db:
    image: mongo:latest
    volumes:
      - /usr/local/var/mongodb:/data/db

  app:
    container_name: notes-app
    command: npm run start
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/public:/usr/src/app/public
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=notes.skivri.local

  server: 
    container_name: notes-server
    build: server
    secrets:
      - APP_SECRET
  
secrets:
  APP_SECRET:
    external: true

networks:
  default:
    external:
      name: nginx-proxy