version: '3.6'

services:
  db:
    image: mongo:latest
    volumes:
      - /usr/local/var/mongodb:/data/db

  app:
    container_name: notes-app
    build:
      context: ./app
      dockerfile: Dockerfile-dev
    image: registry.skivri.ge:443/notes-app
    volumes:
      - './app/app:/usr/src/app/app'
    ports:
      - 8081:8080
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=notes.skivri.local

  server: 
    container_name: notes-server
    build: server
    image: registry.skivri.ge:443/notes-server
    secrets:
      - APP_SECRET
      - FIRST_USER
      - FIRST_USER_PASSWORD
      - OTP_SECRET
  
secrets:
  APP_SECRET:
    external: true
  FIRST_USER:
    external: true
  FIRST_USER_PASSWORD:
    external: true
  OTP_SECRET:
    external: true

networks:
  default:
    external:
      name: nginx-proxy