version: '3.6'

services:
  db:
    image: mongo:latest
    volumes:
      - /var/mongo_data:/data/db

  app:
    container_name: notes-app
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    image: registry.skivri.ge:443/notes-app
    ports:
      - 5000:80
    volumes:
      - /etc/letsencrypt/live/notes.skivri.ge:/certs

  server: 
    container_name: notes-server
    build: server
    image: registry.skivri.ge:443/notes-server
    secrets:
      - APP_SECRET
      - FIRST_USER
      - FIRST_USER_PASSWORD
      - OTP_SECRET
  
secrets:
  APP_SECRET:
    external: true
  FIRST_USER:
    external: true
  FIRST_USER_PASSWORD:
    external: true
  OTP_SECRET:
    external: true