version: '3.6'

services:
  app:
    container_name: notes-app
    build:
      context: ./app
      dockerfile: Dockerfile-prod
    image: registry.skivri.ge:443/notes-app
    environment:
      - VIRTUAL_HOST=notes.skivri.ge

  server: 
    container_name: notes-server
    build: server
    image: registry.skivri.ge:443/notes-server
    secrets:
      - APP_SECRET
  
secrets:
  APP_SECRET:
    external: true

networks:
  default:
    external:
      name: nginx-proxy